language: java
deploy:
  provider: heroku
  api_key:
    secure: H6YuLMejWPRATunsOXvRktLmCcjPFretsBgkhLWJjYgVWuKURJ6OCkZNYmeAuDNyUicDLp30qp9rUXD2T/sigD/4zPajIRMAGyp0zvK1+UnXqC2r1BXU78Hdhxr+8XlyYlI2tJ9+JluhfTMgVT/jfHawU7QiG5riwsgu757F2uTDjNNC7MG1LjWdGCNW1Zbo0OLGbpRSmtUIswmHnAYbKTAn8Us2pl1BgHSqFzWBEOlf2kc7AovVbiIRhLXPLreYQbVR4FOEesf9ENa1KlQnM6TIXgNIgPPzc4+NKErW9/+08DHqYm1DdKW41Q/x9HFk+WfkzOeU2lV22Iv32R7Y0vvKR5Aze2J4L3EBARb56HDeWc8Bfj47QSSdGulIgWaHPoOnIGOWcJC0FhsGolC4+3uNHaNruwzIzlB8tnWIVVxB0nPz9QzJmVi23fiOTuMnNcDIqbEX53mmU7MNEbqQBrkPqb7GMnkZK9aLNDFUf4DbgMyzua4ZY39rAF8vMmkJnTENnP1Y93asWYjpyKWH8otLLRbLlud1ep+hvgV8g2kddDcwBrOF+yfK7l9HnYni8UIN6XxVMy5HFdBVP/Dovg/Syx4Vb/rBgnbT1KoMBxh/TRhi4jphoDiS/u7ZtNapZinW5Gq6QPoHu+3SLkmJYW6eglYIsdCePlgqbDMbX7k=
  app: glacial-falls-61571
